import { Ticket, ProgressUpdate, TicketStatus, TTRCompliance } from '@/types/ticket';
import { TicketWithProgress, ProgressUpdateRow } from '@/hooks/useTickets';

export const mapDbTicketToTicket = (dbTicket: TicketWithProgress): Ticket => ({
  id: dbTicket.id,
  provider: dbTicket.provider || 'TSEL',
  stakeHolder: dbTicket.stake_holder || undefined,
  hsa: dbTicket.hsa || undefined,
  sto: dbTicket.sto || undefined,
  odc: dbTicket.odc || undefined,
  datek: dbTicket.datek || undefined,
  losNonLos: dbTicket.los_non_los || undefined,
  siteImpact: dbTicket.site_impact || undefined,
  classSite: dbTicket.class_site || undefined,
  tacc: dbTicket.tacc || undefined,
  tim: dbTicket.tim || undefined,
  incNumbers: dbTicket.inc_numbers,
  idPelanggan: dbTicket.id_pelanggan || undefined,
  namaPelanggan: dbTicket.nama_pelanggan || undefined,
  siteCode: dbTicket.site_code,
  siteName: dbTicket.site_name,
  networkElement: dbTicket.network_element || undefined,
  kategori: dbTicket.kategori || '',
  lokasiText: dbTicket.lokasi_text || '',
  latitude: dbTicket.latitude || undefined,
  longitude: dbTicket.longitude || undefined,
  jarakKmRange: dbTicket.jarak_km_range?.toString() || undefined,
  ttrCompliance: (dbTicket.ttr_compliance || 'COMPLY') as TTRCompliance,
  penyebabNotComply: dbTicket.penyebab_not_comply || undefined,
  jamOpen: new Date(dbTicket.jam_open),
  ttrTargetHours: dbTicket.ttr_target_hours,
  maxJamClose: new Date(dbTicket.max_jam_close),
  ttrRealHours: dbTicket.ttr_real_hours || undefined,
  sisaTtrHours: dbTicket.sisa_ttr_hours,
  status: (dbTicket.status || 'OPEN') as TicketStatus,
  isPermanent: dbTicket.is_permanent,
  permanentNotes: dbTicket.permanent_notes || undefined,
  penyebab: dbTicket.penyebab || undefined,
  segmen: dbTicket.segmen || undefined,
  incGamas: dbTicket.inc_gamas || undefined,
  kjd: dbTicket.kjd || undefined,
  teknisiList: dbTicket.teknisi_list || undefined,
  assignedTo: dbTicket.assigned_to || undefined,
  assignedAt: dbTicket.assigned_at ? new Date(dbTicket.assigned_at) : undefined,
  assignedBy: dbTicket.assigned_by || undefined,
  createdByAdmin: dbTicket.created_by || '',
  createdAt: new Date(dbTicket.created_at),
  updatedAt: new Date(dbTicket.updated_at),
  rawTicketText: dbTicket.raw_ticket_text || undefined,
  progressUpdates: dbTicket.progress_updates?.map(mapDbProgressToProgress) || [],
  adminNotes: dbTicket.admin_notes || undefined,
  perbaikan: dbTicket.perbaikan || undefined,
  statusAlatBerat: dbTicket.status_alat_berat || undefined,
  timelineDispatch: dbTicket.timeline_dispatch || undefined,
  timelinePrepare: dbTicket.timeline_prepare || undefined,
  timelineOtw: dbTicket.timeline_otw || undefined,
  timelineIdentifikasi: dbTicket.timeline_identifikasi || undefined,
  timelineBreak: dbTicket.timeline_break || undefined,
  timelineSplicing: dbTicket.timeline_splicing || undefined,
  kendala: dbTicket.kendala || undefined,
  atbt: dbTicket.atbt || undefined,
  tiketEksternal: dbTicket.tiket_eksternal || undefined,
});

export const mapDbProgressToProgress = (pu: ProgressUpdateRow): ProgressUpdate => ({
  id: pu.id,
  ticketId: pu.ticket_id,
  timestamp: new Date(pu.timestamp),
  source: pu.source as 'HD' | 'ADMIN' | 'SYSTEM',
  message: pu.message,
  statusAfterUpdate: pu.status_after_update || undefined,
  locationUpdate: pu.location_lat && pu.location_lon 
    ? { lat: pu.location_lat, lon: pu.location_lon } 
    : undefined,
  attachments: pu.attachments || undefined,
  createdBy: pu.created_by || '',
});

export const mapTicketToDbInsert = (ticket: Partial<Ticket>, userId?: string) => ({
  provider: ticket.provider || 'TSEL',
  stakeHolder: ticket.stakeHolder || undefined,
  hsa: ticket.hsa || undefined,
  inc_numbers: ticket.incNumbers || [],
  id_pelanggan: ticket.idPelanggan,
  nama_pelanggan: ticket.namaPelanggan,
  site_code: ticket.siteCode || '',
  site_name: ticket.siteName || '',
  network_element: ticket.networkElement,
  kategori: ticket.kategori || '',
  lokasi_text: ticket.lokasiText || '',
  latitude: ticket.latitude,
  longitude: ticket.longitude,
  jarak_km_range: ticket.jarakKmRange,
  ttr_compliance: ticket.ttrCompliance || 'COMPLY',
  penyebab_not_comply: ticket.penyebabNotComply,
  jam_open: ticket.jamOpen?.toISOString() || new Date().toISOString(),
  ttr_target_hours: ticket.ttrTargetHours || 24,
  max_jam_close: ticket.maxJamClose?.toISOString() || new Date().toISOString(),
  ttr_real_hours: ticket.ttrRealHours,
  sisa_ttr_hours: ticket.sisaTtrHours || 0,
  status: ticket.status || 'OPEN',
  is_permanent: ticket.isPermanent || null,
  permanent_notes: ticket.permanentNotes,
  penyebab: ticket.penyebab,
  segmen: ticket.segmen,
  inc_gamas: ticket.incGamas,
  kjd: ticket.kjd,
  teknisi_list: ticket.teknisiList,
  assigned_to: ticket.assignedTo,
  assigned_at: ticket.assignedAt?.toISOString(),
  assigned_by: ticket.assignedBy,
  created_by: userId,
  raw_ticket_text: ticket.rawTicketText,
  admin_notes: ticket.adminNotes,
  perbaikan: ticket.perbaikan,
  status_alat_berat: ticket.statusAlatBerat,
  timeline_dispatch: ticket.timelineDispatch,
  timeline_prepare: ticket.timelinePrepare,
  timeline_otw: ticket.timelineOtw,
  timeline_identifikasi: ticket.timelineIdentifikasi,
  timeline_break: ticket.timelineBreak,
  timeline_splicing: ticket.timelineSplicing,
  kendala: ticket.kendala,
  atbt: ticket.atbt,
  tiket_eksternal: ticket.tiketEksternal,
});
